### ISSUE TITLE
Display clickable 'diff' link on the upgrade status page

### ISSUE THREAD

**Issue by kalleth** [discourse/docker_manager#23]
When running on the tests-passed branch, it'd be nice to be able to diff the newest version with my current version by having the links to the commit sha's link directly to a github compare view.

For example, if i am currently running a026a7c and the latest available version is fce74e6, I should be able to click a link targeting https://github.com/discourse/discourse/compare/a026a7c...fce74e6 so I can review the changes before I upgrade -- as there doesn't seem to be an available changelog :)

I'm happy to pick this up myself, but I don't have time today or tomorrow (on client work) to set up a development environment for docker_manager (i haven't got a local discourse_docker instance so i'd have to set that up too). Happy to pick this up later in the week if you think this is a good idea :)

**Comment by SamSaffron** [comment]
sure, feel free to pick this up, sounds like a fine idea, be sure to include a screen shot with the PR

**Comment by kalleth** [comment]
OK -- I'll try and give it a go later. Zero experience with Ember though so it might take me a little while :)

**Comment by cpradio** [comment]
This is done.
https://github.com/discourse/docker_manager/pull/28
