### ISSUE TITLE
Would this work on vanilla discourse version?

### ISSUE THREAD

**Issue by steve-ng** [discourse/docker_manager#27]
1) I forked discourse to my repo and checked out stable branch. 

2) I followed this guide to install discourse on Ubuntu: https://meta.discourse.org/t/beginners-guide-to-install-discourse-on-ubuntu-for-development/14727

3) I went inside the plugins folder, and git clone this project. When i go inside admin/upgrade, I could see the user interface for admin/upgrade. 

4) I made some commits in the stable branch and checked-in. 

5) I go admin/upgrade, it doesn't prompt for upgrade to new version. 

Am i doing something wrong?

**Comment by SamSaffron** [comment]
no this does not work on anything except for our official docker install
