### ISSUE TITLE
Getting "ABORTING, you do not have enough unicorn workers running" when running in local development mode

### ISSUE THREAD

**Issue by netdeamon** [discourse/docker_manager#36]
Hi I have installed the plugin, and set it up as described ( by going inside `manager-client` folder and doing `npm` and `bower` install ).
But when I try to upgrade a plugin by using this plugin, I get the above error.

Local setup
OS : Mac OS
Installed using [advanced setup install for mac](https://meta.discourse.org/t/beginners-guide-to-install-discourse-on-mac-os-x-macos-for-development/15772)

**Comment by SamSaffron** [comment]
This is not the right place, can you discuss this on meta.discourse.org

Docker manager only works with unicorn and our official docker image, so I would not expect it to work in dev.
